"-------------常规设置------------------------------------
syntax on	"语法高亮
set nu		"显示行号


"-------------omnicppcomplete设置-------------------------
set nocp 
filetype plugin on
map <C-F12> :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>



"-------------------分割线--------------------------------

set nocompatible

set tabstop=4
set softtabstop=4
set encoding=utf-8
set fileencodings=utf-8
set shiftwidth=4
set cindent
set cinoptions={0,1s,t0,n-2,p2s,(03s,=.5s,>1s,=1s,:1s

